# backend/docker-compose.yml
services:
  auth-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-microservice
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/auth-db
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
    depends_on:
      - mongodb
    networks:
      - my-custom-network  # Red externa
    command: yarn start:dev

  mongodb:
    image: mongo:latest
    container_name: auth-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - my-custom-network  # Red externa

networks:
  my-custom-network:
    external: true  # Red existente

volumes:
  mongodb-data:
